[package]
name = "multimizer-cli"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.95"
clap = { version = "4.5.26", features = ["derive"] }
multimizer = { path = "../multimizer-core", features = ["sqlite"] }
